# Site settings
title: Shawn XK
email: xiw69@pitt.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a college student at PITT, this is my personal blog for every thing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shawnxkwang.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  shawnxkwang

# Build settings
markdown: kramdown
